### ISSUE TITLE
Parse inferred typescript types

### ISSUE THREAD

**Issue by jochembeetz** [grantila/typeconv#20]
It would be nice if the plugin would parse Typescript built in types such as: Partial, Pick, Omit etc.
It would make it possible to parse inferred types for example:

```
Interface Comment {
  description: string
  deletedAt: Date
}

Type CommentDTO = Omit<Comment, 'deletedAt'>;
```
Right now this is not possible and I would have to refactor almost all of my types, or duplicate them to have them available in Swagger.

May be inspiring: https://github.com/nestjs/swagger/tree/master/lib/type-helpers

**Comment by grantila** [comment]
`Omit`, `Pick` and `Partial` is now supported, unless you reference other named string unions in the second argument, only inline string literals/unions are supported. This should cover most cases.
