### ISSUE TITLE
Unable to convert `keyof typeof something`

### ISSUE THREAD

**Issue by erkin98** [grantila/typeconv#30]
When converting to try something like this
```
export type DemoType = {
  name: keyof typeof something;
  class: string;
  Pure?: boolean;
}
```
it's converting this type to JSON but doesn't give a type field for the `name`. 
![image](https://user-images.githubusercontent.com/20378722/195857119-c0545814-747a-41b6-87b4-a8e0767322cc.png)

**Comment by grantila** [comment]
The conversion isn't parsing TypeScript _code_, only types. Basically, it can understand `.d.ts`, but not logic in `.ts` files.

If you run tsc to compile that file and generate a separate declaration file, _that_ file can be used as input to typeconv.
