### ISSUE TITLE
Executing typeconv from nmp-scripts or within bash script does not work

### ISSUE THREAD

**Issue by sml86** [grantila/typeconv#31]
```
$ npm run convert-types

> @***/***@*** convert-types
> npx typeconv -f ts -t oapi -o docs './src/**/*.ts

💡 Converted 0 types in 0 files, in 0.0s
```

```
$ npm run convert-types

> @***/***@*** convert-types
> typeconv -f ts -t oapi -o docs './src/**/*.ts

💡 Converted 0 types in 0 files, in 0.0s
```

**Comment by RafaelRamosR** [comment]
In this case a single quotation mark seems to be missing at the end.
> ```
> > typeconv -f ts -t oapi -o docs './src/**/*.ts
> ```

However, something similar happens to me:
```
npx typeconv -f ts -t oapi -o spec 'src/api/**/*.d.ts'
💡 Converted 0 types in 0 files, in 0.0s

npx typeconv -f ts -t oapi -o spec './src/api/**/*.d.ts'
💡 Converted 0 types in 0 files, in 0.0s
```

It works when I do not use single quotes or use double quotes:
```
npx typeconv -f ts -t oapi -o spec "src/api/**/*.d.ts"
💡 Converted 38 types in 6 files, in 0.1s

npx typeconv -f ts -t oapi -o spec src/api/**/*.d.ts
💡 Converted 38 types in 6 files, in 0.1s
```

**Comment by grantila** [comment]
What OS and shell are you using?

I assume most users are either on MacOS or some Linux, in which case they probably use bash or zsh, where single quotes work as expected. On other shells, you might need other escaping. The point is to provide a string which the shell _does not_ expand itself, but instead allow typeconv to do it.

**Comment by RafaelRamosR** [comment]
I'm using `Window 10 x64`, but I really don't find it a problem to have to use double quotes. I think this issue could be closed perfectly well.

**Comment by sml86** [comment]
Thank you, used also Windows 10. Did not check with double quotes already but I'm sure, that it will work.
As issue opener, I close it. Thanks again.
