### ISSUE TITLE
TS enum to graphql enum

### ISSUE THREAD

**Issue by xxleyi** [grantila/typeconv#8]
Thrift IDL enum to TS enum has no problem, such as:
![image](https://user-images.githubusercontent.com/12626454/119828197-85d92980-bf2c-11eb-9e33-9a583841873e.png)

typeconv now:
![image](https://user-images.githubusercontent.com/12626454/119828352-ab663300-bf2c-11eb-82bf-98b2b7d76263.png)

I understand not all TS enum has good  correspondence in graphql, bu will typeconv behave better in such case in the future? maybe some options?

**Comment by grantila** [comment]
Not sure how these two relate.

Enums are problematic, and very not portable. What do you expect to get in GraphQL? There's no support for enum _values_, so you'd rather have some sort of string union.

I suggest rethinking using unions at all in this ecosystem of JavaScript, TypeScript, GraphQL, etc. Rather go with string unions.
